#ifndef TOKEN_H
#define TOKEN_H

typedef struct TOKEN_STRUCT{
    enum {
        TOKEN_ID, TOKEN_EQUALS, TOKEN_STRING_VALUE, TOKEN_SEMI, TOKEN_LPAREN, TOKEN_RPAREN,
        TOKEN_LSPAREN, TOKEN_RSPAREN, TOKEN_LBRACKETS, TOKEN_RBRACKETS, TOKEN_BIGGER, TOKEN_LESS,
        TOKEN_COMMA, TOKEN_NOT, TOKEN_INT, TOKEN_FLOAT, TOKEN_DOUBLE, TOKEN_CHAR, TOKEN_STRING,
        TOKEN_BOOL, TOKEN_PLUS, TOKEN_MINUS, TOKEN_MUL, TOKEN_DIV, TOKEN_E0F
    } type;

    char* value;
} token_T;


token_T* init_token(int type, char* value);

#endif